config/routes.rb
Rails.application.routes.draw do

  scope 'admin' do
    resources :broadcast_rooms
    resources :translators
    resources :users
    resources :events
    resources :requests, only: [:show, :index]
    resources :dashboard, only: [:index]
    scope 'auth' do
      devise_for :users
    end
  end

  root "home#index"
  get "event" => 'home#event'
  get "about" => 'home#about'

  resources :admin, only: [:index]

end

app/models/translator.rb
class Translator < ApplicationRecord
  GENDER = ['Male', 'Female', 'Others']
end

app/controllers/translators_controller.rb
class TranslatorsController < ApplicationController
  before_action :set_translator, only: [:show, :edit, :update, :destroy]

  # GET /translators
  def index
    @translators = Translator.all
  end

  # GET /translators/1
  def show
  end

  # GET /translators/new
  def new
    @translator = Translator.new
  end

  # GET /translators/1/edit
  def edit
  end

  # POST /translators
  def create
    @translator = Translator.new(translator_params)

    if @translator.save
      redirect_to @translator, notice: 'Translator was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /translators/1
  def update
    if @translator.update(translator_params)
      redirect_to @translator, notice: 'Translator was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /translators/1
  def destroy
    @translator.destroy
    redirect_to translators_url, notice: 'Translator was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_translator
      @translator = Translator.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def translator_params
      params.require(:translator).permit(:name, :email, :phone, :gender)
    end
end

app/views/translators/_form.html.haml
= simple_form_for(@translator) do |f|
  = f.error_notification

  = f.input :name
  = f.input :email
  = f.input :phone
  = f.input :gender, collection: Translator::GENDER
  
  = f.button :submit, class: 'btn btn-primary'

app/views/translators/edit.html.haml
.page-title
  %h4 Editing Translator

.card
  .card-block
    %h4.card-title Form Translator

    = render 'form'
    %hr
    = link_to translators_path, class: 'btn btn-default' do
      %i.fa.fa-chevron-left
      Back

    = link_to @translator, class: 'btn btn-info' do
      %i.fa.fa-eye
      Show

app/views/translators/index.html.haml
.page-title
  %h4 Translators

.card
  .card-block
    %h4.card-title Listing Translators
    .pull-right
      = link_to new_translator_path, class: 'btn btn-primary' do
        = fa_icon 'plus'
        New Translator

    %table.table.table-striped
      %thead
        %tr
          %th Name
          %th Email
          %th Phone
          %th Gender
          %th.text-right Actions

      %tbody
        - @translators.each do |translator|
          %tr
            %td= translator.name
            %td= translator.email
            %td= translator.phone
            %td= translator.gender
            %td.text-right
              = link_to translator, class: 'btn btn-info' do
                = fa_icon 'eye'
                Show
              = link_to [:edit, translator], class: 'btn btn-primary' do
                = fa_icon 'edit'
                Edit
              = link_to translator, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do
                = fa_icon 'trash'
                Delete

app/views/translators/new.html.haml
.page-title
  %h4 Translators

.card
  .card-block
    %h4.card-title New Translator

    = render 'form'
    %hr
    = link_to translators_path, class: 'btn btn-default' do
      %i.fa.fa-chevron-left
      Back

app/views/translators/show.html.haml
.page-title
  %h4 Translators
.card
  .card-block
    %h4.card-title Show Translator
    %hr
  .mrg-top-20
    %table.table
      %col{width: 10}
      %col{width: 300}
      %tr
        %th Name :
        %td= @translator.name
      %tr
        %th Email :
        %td= @translator.email
      %tr
        %th Phone :
        %td= @translator.phone

      %tr
        %th Gender :
        %td= @translator.gender

    %hr
    .mrg-top-25
      = link_to translators_path, class: 'btn btn-default' do
        %i.fa.fa-chevron-left
        Back
      = link_to [:edit, @translator], class: 'btn btn-primary' do
        %i.fa.fa-edit
        Edit