config/routes.rb
Rails.application.routes.draw do

  scope 'admin' do
    resources :broadcast_rooms
    resources :translators
    resources :users
    resources :events
    resources :requests, only: [:show, :index]
    resources :dashboard, only: [:index]
    scope 'auth' do
      devise_for :users
    end
  end

  root "home#index"
  get "event" => 'home#event'
  get "about" => 'home#about'

  resources :admin, only: [:index]

end

app/views/partials/_footer.html.haml
.footer{style: 'padding: 10px'}
  .copyright
    %span
      Copyright © 2017
      = succeed "." do
        %b.text-dark Codingate
    %span.go-right
      %a.text-gray.mrg-right-15{:href => ""} Term &amp; Conditions
      %a.text-gray{:href => ""} Privacy &amp; Policy

app/views/partials/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light{style: 'background-color: #E91E63'}
  %a.navbar-brand{:href => "/"} Broadcast Translation
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        %a.nav-link{:href => "/"}
          Home
          %span.sr-only (current)
      %li.nav-item
        %a.nav-link{:href => "/event"} Event
      %li.nav-item
        %a.nav-link{:href => "/about"} About
    %ul.navbar-nav.ml-auto
      %li.nav-item
        %a.nav-link{:href => "#"} Signin 

app/views/partials/_side-panel.html.haml
.side-panel-wrapper.bg-white
  %ul.nav.nav-tabs{:role => "tablist"}
    %li.nav-item.active
      %a.nav-link{"data-toggle" => "tab", :href => "index.html#chat", :role => "tab"}
        %span Chat
    %li.nav-item
      %a.nav-link{"data-toggle" => "tab", :href => "index.html#profile", :role => "tab"}
        %span Profile
    %li.nav-item
      %a.nav-link{"data-toggle" => "tab", :href => "index.html#todo-list", :role => "tab"}
        %span Todo
    %li.panel-close
      %a.side-panel-toggle{:href => "javascript:void(0);"}
        %i.ti-close
  .tab-content
    / chat START
    #chat.tab-pane.fade.in.active{:role => "tabpanel"}
      .chat
        .chat-user-list.scrollable
          .chat-section
            %h5.chat-title Recent
            
          .chat-section
            %h5.chat-title Members
            
        .conversation
          .conversation-wrapper
            .conversation-header
              %a.back.chat-toggle{:href => "javascript:void(0);"}
                %i.ti-arrow-circle-left
              %span.user-name Jordan Hurst
            .conversation-body
              .msg
                .bubble.me
                  %span Feeling all right, sir?
              .msg
                .bubble.friend
                  %span Just like new
              .msg
                .bubble.friend
                  %span How about you?
              .msg
                .bubble.me
                  %span Right now I feel I could take on the whole Empire myself
              .msg
                .bubble.friend
                  %span All right
            .conversation-footer
              %button.upload-btn
                %i.ti-camera
              %input.chat-input{:placeholder => "Type a message...", :type => "text"}/
              %button.sent-btn
                %i.fa.fa-send-o
    / chat END
    / profile START
    #profile.tab-pane.fade{:role => "tabpanel"}
      .profile.scrollable
        
    / profile END
    / todo START
    #todo-list.tab-pane.fade{:role => "tabpanel"}
      .todo-wrapper
        .todo-category-wrapper
          
          

app/views/partials/_sidebar.html.haml
.side-nav-inner
  .side-nav-logo
    %a{:href => "index.html"}
      .logo.logo-dark{:style => "background-image: url('/assets/images/logo/logo.png')"}
      .logo.logo-white{:style => "background-image: url('/assets/images/logo/logo-white.png')"}
    .mobile-toggle.side-nav-toggle
      %a{:href => ""}
        %i.ti-arrow-circle-left

  %ul.side-nav-menu.scrollable

    %li.nav-item.active
      = link_to root_url, class: 'mrg-top-30' do
        %span.icon-holder
          %i.ti-home
        %span.title Dashboard

    %li.nav-item
      = link_to translators_url do
        %span.icon-holder
          %i.ti-user
        %span.title Translators

    %li.nav-item
      = link_to users_url do
        %span.icon-holder
          %i.ti-user
        %span.title User

    %li.nav-item
      = link_to events_url do
        %span.icon-holder
          %i.ti-video-clapper
        %span.title Event

    %li.nav-item
      = link_to broadcast_rooms_url do
        %span.icon-holder
          %i.ti-announcement
        %span.title Broadcast Room
        
    %li.nav-item
      = link_to requests_url do
        %span.icon-holder
          %i.ti-alert
        %span.title Request
        
    

app/views/partials/_top-nav.html.haml
.header-container
  %ul.nav-left
    %li
      %a.side-nav-toggle{:href => "javascript:void(0);"}
        %i.ti-view-grid
    %li.search-box
      %a.search-toggle.no-pdd-right{:href => "javascript:void(0);"}
        %i.search-icon.ti-search.pdd-right-10
        %i.search-icon-close.ti-close.pdd-right-10
    %li.search-input
      %input.form-control{:placeholder => "Search...", :type => "text"}/
      .advanced-search
        .search-wrapper
          .pdd-vertical-10
            %span.display-block.mrg-vertical-5.pdd-horizon-20.text-gray
              %i.ti-user.pdd-right-5
              %span People
            %ul.list-unstyled.list-info
              %li
                %a{:href => ""}
                  %img.thumb-img{:alt => "", :src => "assets/images/avatars/thumb-1.jpg"}/
                  .info
                    %span.title Jordan Hurst
                    %span.sub-title
                      %i.ti-location-pin
                      %span 44 Shirley Ave. West Chicago
              %li
                %a{:href => ""}
                  %img.thumb-img{:alt => "", :src => "assets/images/avatars/thumb-5.jpg"}/
                  .info
                    %span.title Jennifer Watkins
                    %span.sub-title
                      %i.ti-location-pin
                      %span 514 S. Magnolia St. Orlando
              %li
                %a{:href => ""}
                  %img.thumb-img{:alt => "", :src => "assets/images/avatars/thumb-4.jpg"}/
                  .info
                    %span.title Michael Birch
                    %span.sub-title
                      %i.ti-location-pin
                      %span 70 Bowman St. South Windsor
          .mrg-horizon-20.border.top
          .pdd-vertical-10
            %span.display-block.mrg-vertical-5.pdd-horizon-20.text-gray
              %i.ti-rss.pdd-right-5
              %span Post
            %ul.list-unstyled.list-info
              %li
                %a{:href => ""}
                  %img.thumb-img{:alt => "", :src => "assets/images/img-1.jpg"}/
                  .info
                    %span.title Artoo expresses his relief
                    %span.sub-title
                      %span Oh, thank goodness we're coming out...
              %li
                %a{:href => ""}
                  %img.thumb-img{:alt => "", :src => "assets/images/img-2.jpg"}/
                  .info
                    %span.title Ready for some power?
                    %span.sub-title
                      %span Lord Vader. You may take Caption So...
        .search-footer
          %span
            You are Searching for '
            %b.text-dark>
              %span.serach-text-bind
            '
  %ul.nav-right
    %li.user-profile.dropdown
      %a.dropdown-toggle{"data-toggle" => "dropdown", :href => ""}
        %img.profile-img.img-fluid{:alt => "", :src => "assets/images/user.jpg"}/
        .user-info
          %span.name.pdd-right-5 Nate Leong
          %i.ti-angle-down.font-size-10
      %ul.dropdown-menu
        %li
          %a{:href => ""}
            %i.ti-settings.pdd-right-10
            %span Setting
        %li
          = link_to edit_user_registration_path do
            %i.ti-user.pdd-right-10
            %span Profile
        %li
          %a{:href => ""}
            %i.ti-email.pdd-right-10
            %span Inbox
        %li.divider{:role => "separator"}
        %li
          = link_to destroy_user_session_path do
            %i.ti-power-off.pdd-right-10
            Logout

    %li.notifications.dropdown
      %a.dropdown-toggle{"data-toggle" => "dropdown", :href => ""}
        %i.ti-bell
      %ul.dropdown-menu
        %li.notice-header
          %i.ti-bell.pdd-right-10
          %span Notifications
        %li
          %ul.list-info.overflow-y-auto.relative.scrollable
            %li
              %a{:href => ""}
                %img.thumb-img{:alt => "", :src => "assets/images/avatars/thumb-5.jpg"}/
                .info
                  %span.title
                    %span.font-size-14.text-semibold Jennifer Watkins
                    %span.text-gray
                      commented on your
                      %span.text-dark post
                  %span.sub-title 5 mins ago
           
        %li.notice-footer
          %span
            %a.text-gray{:href => ""}
              Check all notifications
              %i.ei-right-chevron.pdd-left-5.font-size-10
    %li
      %a.side-panel-toggle{:href => "javascript:void(0);"}
        %i.ti-align-right