config/routes.rb
Rails.application.routes.draw do

  scope 'admin' do
    resources :broadcast_rooms
    resources :translators
    resources :users
    resources :events
    resources :requests, only: [:show, :index]
    resources :dashboard, only: [:index]
    scope 'auth' do
      devise_for :users
    end
  end

  root "home#index"
  get "event" => 'home#event'
  get "about" => 'home#about'

  resources :admin, only: [:index]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events

  mount_uploader :avatar, TumbnailUploader
  
  ROLES = ['Super', 'Admin']

  ROLES.each do |role_name|
   scope role_name.downcase, -> { where(role: role_name) }
   define_method "#{role_name.downcase.parameterize.underscore}?" do
     role == role_name
   end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    if @user.update_without_password(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :role, :password, :avatar, :avatar_cache)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification

  .image-uploader{align: 'center'}
    %a{:href => "#!"}
      = image_tag f.object.avatar, class: 'img-responsive', size: '150x150'
    = f.input :avatar, as: :file, label: 'Upload Image', 
      :label_html => { class: 'btn btn-default'}
    = f.hidden_field :avatar_cache

  = f.input :name
  = f.input :role, collection: User::ROLES
  = f.input :email

  = f.input :password

  = f.button :submit, class: 'btn btn-primary'

app/views/users/edit.html.haml
.page-title
  %h4 Users

.card
  .card-block
    %h4.card-title Editing User

    = render 'form'
    %hr
    = link_to users_path, class: 'btn btn-default' do
      %i.fa.fa-chevron-left
      Back
    = link_to @user, class: 'btn btn-info' do
      %i.fa.fa-eye
      Show

app/views/users/index.html.haml
.page-title
  %h4 Users

.card
  .card-block
    %h4.card-title Listing Users
    .pull-right
      = link_to new_user_path, class: 'btn btn-primary' do
        = fa_icon 'plus'
        New User

    %table.table.table-striped
      %thead
        %tr
          %th Name 
          %th Role
          %th Email
          %th.text-right Actions

      %tbody
        - @users.each do |user|
          %tr
            %td= user.name
            %td= user.role
            %td= user.email
            %td.text-right
              = link_to user, class: 'btn btn-info' do
                = fa_icon 'eye'
                Show
              = link_to [:edit, user], class: 'btn btn-primary' do
                = fa_icon 'edit'
                Edit
              = link_to user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do
                = fa_icon 'trash'
                Delete

app/views/users/new.html.haml
.page-title
  %h4 Users

.card
  .card-block
    %h4.card-title New User

    = render 'form'
    %hr
    = link_to users_path, class: 'btn btn-default' do
      %i.fa.fa-chevron-left
      Back

app/views/users/show.html.haml
%page.title
  %h4 User
%p#notice= notice
.card
  .card-block
    %h4.card-title Show User
  .mrg-top-20
    %div{align: 'center'}
      = image_tag @user.avatar_url, size: '150x150'
    %br
    %table.table
      %col{width: 10}
      %col{width: 300}
      %tr
        %th Name :
        %td= @user.name
      %tr
        %th Email :
        %td= @user.email
    %hr
    .mrg-top-25
      = link_to users_path, class: 'btn btn-default' do
        %i.fa.fa-cheveron-left
        Back
      = link_to [:edit, @user], class: 'btn btn-primary' do
        %i.fa.fa-edit
        Edit