config/routes.rb
Rails.application.routes.draw do

  scope 'admin' do
    resources :broadcast_rooms
    resources :translators
    resources :users
    resources :events
    resources :requests, only: [:show, :index]
    resources :dashboard, only: [:index]
    scope 'auth' do
      devise_for :users
    end
  end

  root "home#index"
  get "event" => 'home#event'
  get "about" => 'home#about'

  resources :admin, only: [:index]

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  mount_uploader :thumbnail, TumbnailUploader
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = current_user.events.new(event_params)

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def event_params
      params.require(:event).permit(:title, :venue, :start_date, :end_date, :thumbnail, :thumbnail_cache)
    end
end

app/views/events/_form.html.haml
= simple_form_for(@event) do |f|
  = f.error_notification

  .image-uploader{align: 'center'}
    %a{:href => "#!"}
      = image_tag f.object.thumbnail, class: 'img-responsive', size: '150x150'
    = f.input :thumbnail, as: :file, label: 'Upload Image', 
      :label_html => { class: 'btn btn-default'}
    = f.hidden_field :thumbnail_cache

  = f.input :title
  = f.input :venue
  = f.input :start_date
  = f.input :end_date

  = f.button :submit, class: 'btn btn-primary'

app/views/events/edit.html.haml
.page-title
  %h4 Events

.card
  .card-block
    %h4.card-title Editing Event

    = render 'form'
    %hr
    = link_to events_path, class: 'btn btn-default' do
      %i.fa.fa-chevron-left
      Back
    = link_to @event, class: 'btn btn-info' do
      %i.fa.fa-eye
      Show

app/views/events/index.html.haml
.page-title
  %h4 Event

.card
  .card-block
    %h4.card-title Listing Events
    .pull-right
      = link_to new_event_path, class: 'btn btn-primary' do
        = fa_icon 'plus'
        New Event

    %table.table.table-striped
      %thead
        %tr
          %th Title
          %th Venue
          %th Start date
          %th End date
          %th User
          %th.text-right Actions

      %tbody
        - @events.each do |event|
          %tr
            %td= event.title
            %td= event.venue
            %td= event.start_date
            %td= event.end_date
            %td= event.user.name
            %td.text-right
              = link_to event, class: 'btn btn-info' do
                = fa_icon 'eye'
                Show
              = link_to [:edit, event], class: 'btn btn-primary' do
                = fa_icon 'edit'
                Edit
              = link_to event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do
                = fa_icon 'trash'
                Delete

app/views/events/new.html.haml
.page-title
  %h4 Events

.card
  .card-block
    %h4.card-title New Event

    = render 'form'
    %hr
    = link_to events_path, class: 'btn btn-default' do
      %i.fa.fa-chevron-left
      Back

app/views/events/show.html.haml
%page.title
  %h4 Event
%p#notice= notice
.card
  .card-block
    %h4.card-title Show Event
  .mrg-top-20
    %div{align: 'center'}
      = image_tag @event.thumbnail_url, size: '150x150'
    %br
    %table.table
      %col{width: 10}
      %col{width: 300}
      %tr
        %th Name :
        %td= @event.title
      %tr
        %th Venue :
        %td= @event.venue
      %tr
        %th Start date:
        %td= @event.start_date
      %tr
        %th End date:
        %td= @event.end_date
      %tr
        %th Created by:
        %td= @event.user.name
         
        
    %hr
    .mrg-top-25
      = link_to events_path, class: 'btn btn-default' do
        %i.fa.fa-chevron-left
        Back
      = link_to [:edit, @event], class: 'btn btn-primary' do
        %i.fa.fa-edit
        Edit